// <auto-generated />
using GreenThumbDb.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumbDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231205090933_SeedDataInstructions")]
    partial class SeedDataInstructions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GreenThumbDb.Models.Garden", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GreenThumbDb.Models.GardenPlants", b =>
                {
                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<int>("GardenId")
                        .HasColumnType("int")
                        .HasColumnName("garden_id");

                    b.HasKey("PlantId", "GardenId");

                    b.HasIndex("GardenId");

                    b.ToTable("GardenPlants");
                });

            modelBuilder.Entity("GreenThumbDb.Models.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cacti require four to six hours of bright sunlight daily. ",
                            Name = "Cactus: Light",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "During the spring and summer, give the cactus water every ten days.During the winter rest period, decrease waterings to once every four weeks. ",
                            Name = "Cactus: Water",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = " Nasturtium grows best in soil with a neutral pH (6 to 8) and can tolerate dry conditions, although a moderate amount of moisture is appreciated. ",
                            Name = "Nasturtium: Soil",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nasturtiums prefer weekly watering, but can be watered more often when planted in a greenhouse or in a sunny vegetable plot",
                            Name = "Nasturium: Water",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nasturtiums grow and bloom best when planted in an area of full sun that receives six to eight hours of direct sunlight daily.",
                            Name = "Nasturium: Light",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Give your tea olive shrub at least one inch of water per week, either through rainfall or manual watering methods.",
                            Name = "Tea Olive: Water",
                            PlantId = 4
                        },
                        new
                        {
                            Id = 7,
                            Description = "Roses like six hours of sun per day, it does matter what part of the day those six hours come from",
                            Name = "Rose: Light",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "It is best to water roses twice a week—and water them thoroughly. It's better to water deeply twice per week than to water less deeply more often.",
                            Name = "Rose: Water",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Roses can survive periodic weather extremes, but they prefer temperatures between 60 and 70 degrees Fahrenheit and a humidity range between 60% and 70%.",
                            Name = "Rose: Temperature",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Teddy Bear' sunflower needs full sun; a six to eight hours of bright, direct sunlight daily.",
                            Name = "Teddy bear Sunflower: Light",
                            PlantId = 5
                        },
                        new
                        {
                            Id = 11,
                            Description = "Teddy Bear' sunflowers need one inch of water weekly depending on rainfall amounts and soil conditions. Avoid overwatering as this can lead to root rot and cause stems to become unstable. ",
                            Name = "Teddy bear Sunflower: Water",
                            PlantId = 5
                        },
                        new
                        {
                            Id = 12,
                            Description = "Violas prefer sun over shade, but they don't like heat.",
                            Name = "Viola: Light",
                            PlantId = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "Pansies and the other violas are best grown in humusy, moist soil, such as a peat-based potting mix, or garden soil heavily amended with organic material. ",
                            Name = "Viola: Soil",
                            PlantId = 6
                        },
                        new
                        {
                            Id = 14,
                            Description = "Water Viola regularly, but allow the soil to dry out between waterings.",
                            Name = "Viola: Water",
                            PlantId = 6
                        },
                        new
                        {
                            Id = 15,
                            Description = "Easter lilies prefer to grow in full sun to partial shade, with protection from the strong afternoon sun during the heat of the day",
                            Name = "Easter Lily: Light",
                            PlantId = 7
                        },
                        new
                        {
                            Id = 16,
                            Description = "Easter lily flowers prefer well-drained soil that’s rich in organic matter, although they'll grow in a variety of soil types as long as the drainage is sufficient.",
                            Name = "Easter Lily: Soil",
                            PlantId = 7
                        },
                        new
                        {
                            Id = 17,
                            Description = "Easter lilies like evenly moist soil, so whenever the top inch of soil dries out, water the plants until water starts draining from the bottom. Never allow the plants to sit in water, but also don’t let the soil dry out completely.",
                            Name = "Easter Lily: Water",
                            PlantId = 7
                        },
                        new
                        {
                            Id = 18,
                            Description = "Artichokes require lots of moisture for best growth. Deeply water artichoke plants at planting time, and water them deeply at least once or twice per week.",
                            Name = "Artichoke: Water",
                            PlantId = 8
                        },
                        new
                        {
                            Id = 19,
                            Description = "Artichokes prefer sandy, well-drained but fertile soil. A soil pH slightly on the alkaline side is best.",
                            Name = "Artichoke: Soil",
                            PlantId = 8
                        },
                        new
                        {
                            Id = 20,
                            Description = "Fuchsias are happiest with temperatures between 55 and 80 degrees Fahrenheit, though some heat-tolerant cultivars will keep their blooms up to 90 degrees Fahrenheit.",
                            Name = "Fuschsia: Temperature",
                            PlantId = 9
                        },
                        new
                        {
                            Id = 21,
                            Description = "Fuchsias like to be moist but not soggy. They thrive in humidity, so if you live somewhere dry, they are a little more challenging to grow and keep hydrated.",
                            Name = "Fuschsia: Water",
                            PlantId = 9
                        },
                        new
                        {
                            Id = 22,
                            Description = ". Water Jalapeño when the soil feels dry about an inch down, but don't allow the soil to become waterlogged.",
                            Name = "Jalapeño: Water",
                            PlantId = 10
                        },
                        new
                        {
                            Id = 23,
                            Description = "Plant jalapeño peppers in full sun, meaning at least six hours of direct sunlight on most days.",
                            Name = "Jalapeño: Light",
                            PlantId = 10
                        },
                        new
                        {
                            Id = 24,
                            Description = "A site with partial sun is ideal for shooting star plants.",
                            Name = "Shooting Star: Light",
                            PlantId = 11
                        },
                        new
                        {
                            Id = 25,
                            Description = "Shooting star plants grow and colonize areas of well-draining or sandy loam, although they will tolerate some clay soils.",
                            Name = "Shooting Star: Soil",
                            PlantId = 11
                        },
                        new
                        {
                            Id = 26,
                            Description = "Young zebra grass needs regular watering to get established, but a mature specimen will serve as a drought-tolerant ornamental grass.",
                            Name = "Zebra grass: Water",
                            PlantId = 12
                        },
                        new
                        {
                            Id = 27,
                            Description = "Provide full sun for optimal growth. If the plant is in too much shade, the leaf blades can get floppy, but you can provide a stake or even a tomato cage to help prop them upright.",
                            Name = "Zebra grass: Light",
                            PlantId = 12
                        },
                        new
                        {
                            Id = 28,
                            Description = "Vanilla bean orchid grows best in shade, but these plants will tolerate short periods of morning sun with indirect light.",
                            Name = "Vanilla Bean Orchid: Light",
                            PlantId = 13
                        },
                        new
                        {
                            Id = 29,
                            Description = "Watering a vanilla bean orchid means keeping both the growing medium and the wooden trellis structure damp, because the plant is developing \"air roots\" that draw moisture from the air. ",
                            Name = "Vanilla Bean Orchid: Water",
                            PlantId = 13
                        },
                        new
                        {
                            Id = 30,
                            Description = "The harebell does best when its planted in full sun to partial shade.",
                            Name = "Harebell: Light",
                            PlantId = 14
                        },
                        new
                        {
                            Id = 31,
                            Description = "These wildflowers like deep, infrequent waters that come from natural rainfall. However, newly established plants benefit from frequent watering.",
                            Name = "Harebell: Water",
                            PlantId = 14
                        },
                        new
                        {
                            Id = 32,
                            Description = "Well-draining soil is crucially important for the harebell. Consistently moist soil can lead to root rot. ",
                            Name = "Harebell: Soil",
                            PlantId = 14
                        },
                        new
                        {
                            Id = 33,
                            Description = "While it may be surprising for a plant that grows primarily underground, garlic loves light. To ensure the best chance at growing success, plant your garlic in a spot that receives full sunlight for at least six to eight hours a day.",
                            Name = "Garlic: Light",
                            PlantId = 15
                        },
                        new
                        {
                            Id = 34,
                            Description = "Garlic doesn't have a ton of water requirements. It generally likes its soil moist and should receive around an inch of water per week, with a slight increase if the weather is especially warm. ",
                            Name = "Garlic: Water",
                            PlantId = 15
                        },
                        new
                        {
                            Id = 35,
                            Description = "Camellias thrive in partial shade or in locations that receive dappled sunlight for the entire day, such as the understory beneath tall airy trees.",
                            Name = "Camellia: Light",
                            PlantId = 16
                        },
                        new
                        {
                            Id = 36,
                            Description = "Camellias require well-drained soil, and an ideal soil pH for camellias is within the 6.0 to 6.5 range—slightly acidic.",
                            Name = "Camellia: Soil",
                            PlantId = 16
                        },
                        new
                        {
                            Id = 37,
                            Description = "Twice-a-week watering for a total of one inch of water per week is a good watering schedule. Apply a three-inch layer of mulch to moderate soil temperatures, retain soil moisture, and stifle weeds.",
                            Name = "Camellia: Water",
                            PlantId = 16
                        },
                        new
                        {
                            Id = 38,
                            Description = "Water regularly especially during hot weather. Keep soil moist but not waterlogged because these plants are vulnerable to crown rot.",
                            Name = "Delphinium: Water",
                            PlantId = 17
                        },
                        new
                        {
                            Id = 39,
                            Description = "Delphiniums put on their best show in plenty of sun, 6 to 8 hours daily. However, this is not a plant that does well in dry heat. A location that offers morning sun with light afternoon shade during hot weather can improve and extend flowering.",
                            Name = "Delphinium: Light",
                            PlantId = 17
                        },
                        new
                        {
                            Id = 40,
                            Description = "Once sprouted, water your dahlias once or twice a week. Make sure to water deeply, as large tubers may be planted six inches deep.",
                            Name = "Dahlia: Water",
                            PlantId = 18
                        },
                        new
                        {
                            Id = 41,
                            Description = "Dahlias prefer rich, loamy soil with plenty of organic matter that drains well. ",
                            Name = "Dahlia: Soil",
                            PlantId = 18
                        },
                        new
                        {
                            Id = 42,
                            Description = "Allow the plants to dry between waterings, but not completely. These plants are more susceptible to root rot, so be very careful never to allow them to sit in standing water.",
                            Name = "Dragon Tree: Water",
                            PlantId = 19
                        },
                        new
                        {
                            Id = 43,
                            Description = "Dragon tree prefers a very loose, well-drained potting mix. A succulent/cactus potting mix can work well; or you can make your own mix by blending fine gravel, peat moss, and leaf humus in equal parts.",
                            Name = "Dragon Tree: Soil",
                            PlantId = 19
                        });
                });

            modelBuilder.Entity("GreenThumbDb.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BotanicalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("botanical_name");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("color");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("english_name");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BotanicalName = "Cactaceae",
                            Color = "Orange, pink, red, yellow, white",
                            EnglishName = "Cactus",
                            Family = "Cactaceae"
                        },
                        new
                        {
                            Id = 2,
                            BotanicalName = "Tropaeolum ",
                            Color = "Red, orange, pink, yellow, white",
                            EnglishName = "Nasturtium",
                            Family = "Tropaeolaceae"
                        },
                        new
                        {
                            Id = 3,
                            BotanicalName = "Rosa ",
                            Color = "White, red, pink, yellow, orange",
                            EnglishName = "Rose",
                            Family = "Rosaceae"
                        },
                        new
                        {
                            Id = 4,
                            BotanicalName = "Osmanthus fragrans",
                            Color = "White",
                            EnglishName = "Tea Olive",
                            Family = "Oleaceae"
                        },
                        new
                        {
                            Id = 5,
                            BotanicalName = "Helianthus annuus 'Teddy Bear'",
                            Color = "Golden yellow",
                            EnglishName = "Teddy Bear Sunflower",
                            Family = "Asteraceae"
                        },
                        new
                        {
                            Id = 6,
                            BotanicalName = "Viola",
                            Color = "Purple, orange, white, blue, yellow, red",
                            EnglishName = "Viola",
                            Family = "Violaceae"
                        },
                        new
                        {
                            Id = 7,
                            BotanicalName = "Lilium longiflorum",
                            Color = "White, pink",
                            EnglishName = "Easter lily",
                            Family = "Liliaceae"
                        },
                        new
                        {
                            Id = 8,
                            BotanicalName = "Cynara scolymus ",
                            Color = "Purple",
                            EnglishName = "Artichoke",
                            Family = "Asteraceae"
                        },
                        new
                        {
                            Id = 9,
                            BotanicalName = "Fuchsia ",
                            Color = "Red, pink, white, violet, purple",
                            EnglishName = "Fuchsia",
                            Family = "Onagraceae"
                        },
                        new
                        {
                            Id = 10,
                            BotanicalName = "Capiscum annuum",
                            EnglishName = "Jalapeño",
                            Family = "Solanaceae"
                        },
                        new
                        {
                            Id = 11,
                            BotanicalName = "Dodecatheon meadia or Primula meadia",
                            Color = "White, pink, purple",
                            EnglishName = "Shooting star",
                            Family = "Primulaceae"
                        },
                        new
                        {
                            Id = 12,
                            BotanicalName = "Miscanthus sinensis 'Zebrinus",
                            Color = "Silvery white",
                            EnglishName = "Zebra grass",
                            Family = "Poaceae"
                        },
                        new
                        {
                            Id = 13,
                            BotanicalName = "Vanilla plantifolia",
                            Color = "Yellow-green",
                            EnglishName = "Vanilla bean orchid,",
                            Family = "Orchidaceae"
                        },
                        new
                        {
                            Id = 14,
                            BotanicalName = "Campanula rotundifolia",
                            Color = "Blue",
                            EnglishName = "Harebells"
                        },
                        new
                        {
                            Id = 15,
                            BotanicalName = "Allium sativum",
                            EnglishName = "Garlic",
                            Family = "Amaryllidaceae"
                        },
                        new
                        {
                            Id = 16,
                            BotanicalName = "Camellia",
                            Color = "White, pink, red, yellow, or lavender",
                            EnglishName = "Camellia",
                            Family = "Theaceae"
                        },
                        new
                        {
                            Id = 17,
                            BotanicalName = "Delphinium",
                            Color = "Pastel, blue, pink, purple, white",
                            EnglishName = "Delphinium, Larkspur",
                            Family = "Ranunculaceae"
                        },
                        new
                        {
                            Id = 18,
                            BotanicalName = "Dahlia",
                            Color = "Red, Pink, Orange, Yellow, Purple, White",
                            EnglishName = "Dahlia",
                            Family = "Dahlia"
                        },
                        new
                        {
                            Id = 19,
                            BotanicalName = "Dracaena marginata",
                            Color = "White",
                            EnglishName = "Dragon tree",
                            Family = "Asparagaceae"
                        });
                });

            modelBuilder.Entity("GreenThumbDb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GreenThumbDb.Models.Garden", b =>
                {
                    b.HasOne("GreenThumbDb.Models.User", "User")
                        .WithOne("Garden")
                        .HasForeignKey("GreenThumbDb.Models.Garden", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenThumbDb.Models.GardenPlants", b =>
                {
                    b.HasOne("GreenThumbDb.Models.Garden", "Garden")
                        .WithMany("GardenPlants")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenThumbDb.Models.Plant", "Plant")
                        .WithMany("GardenPlants")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumbDb.Models.Instruction", b =>
                {
                    b.HasOne("GreenThumbDb.Models.Plant", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumbDb.Models.Garden", b =>
                {
                    b.Navigation("GardenPlants");
                });

            modelBuilder.Entity("GreenThumbDb.Models.Plant", b =>
                {
                    b.Navigation("GardenPlants");

                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("GreenThumbDb.Models.User", b =>
                {
                    b.Navigation("Garden");
                });
#pragma warning restore 612, 618
        }
    }
}
